name: CI
on:
  push:
    branches:
      - Staging
jobs:
  Auto_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Space-Zoologist/Library
          key: Library-Space-Zoologist-TargetPlatform
          restore-keys: |
            Library-Space-Zoologist-
            Library-
      - name: Build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: Space-Zoologist
          buildsPath: Build
          targetPlatform: WebGL
      - name: 'Upload Build Artifact'
        uses: actions/upload-artifact@v3
        with: 
          name: build-artifact
          path: 'Build/WebGL/WebGL'
  Build_Upload:
    runs-on: ubuntu-latest
    needs: Auto_Build
      - name: 'Download Build Artifact'
        uses: actions/download-artifact@v3
        with: 
          name: build-artifact
          path: 'Build/'
      - name: Copy to Host Repository
        uses: notpresident35/copy_large_folder_to_another_repo_action@1.0.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_folder: 'Build/'
          destination_repo: 'louieGameTeam/ResearchACampusStoryGame'
          destination_folder: 'SpaceZoologist'
          user_email: ${{ secrets.UNITY_EMAIL }}
          user_name: notpresident35
          commit_msg: '[GHA] Updated Space Zoologist build.'